version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.4
    working_directory: /go/src/github.com/ymgyt/gobot
    environment:
      GO111MODULE: "on"
      GOBIN: /go/src/github.com/ymgyt/gobot/bin
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: show version
          command: cat VERSION

      - restore_cache:
          key: mod-{{ "go.sum" }}

      - run:
          name: install module
          command: go mod vendor

      - save_cache:
          key: mod-{{ "go.sum" }}
          paths:
            - /go/pkg/mod
          when: always

      - run:
          name: docker build
          command: go run .circleci/mage.go docker:build

      - run:
          name: docker tag
          command: go run .circleci/mage.go docker:tag

      - run:
          name: docker push
          command: go run .circleci/mage.go docker:push

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master