// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"context"
)

// Injectors from wire.go:

func InitializeService(ctx context.Context) (*Service, func()) {
	config := ProvideConfigSideEffect()
	mongo := ProvideMongo(config)
	users := ProvideUserStore(mongo)
	commandBuilder := ProvideCommandBuilder(users)
	messageHandler := ProvideMessageHandler(commandBuilder)
	slack := ProvideSlack(config, messageHandler, users)
	handlerGroup := ProvideHandlerGroup(config, slack)
	client := ProvideDatastoreClient(ctx, config)
	server := ProvideServer(config, handlerGroup, client)
	service, cleanup := ProvideService(config, slack, server, mongo)
	return service, func() {
		cleanup()
	}
}
